version: 2
updates:
  # 前端依赖更新
  - package-ecosystem: "npm"
    directory: "/apps/web"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10
    versioning-strategy: increase
    ignore:
      - dependency-name: "postcss"
        versions: ["8.x"]
      - dependency-name: "zod"
        versions: ["3.x"]

  # 后端依赖更新
  - package-ecosystem: "npm"
    directory: "/apps/server"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10
    versioning-strategy: increase

  # 共享包依赖更新
  - package-ecosystem: "npm"
    directory: "/packages/ui"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10
    versioning-strategy: increase

  # GitHub Actions 更新
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly" 